# Generated by Django 5.1 on 2024-08-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='thumbnail',
            field=models.CharField(default='https://parniangostar.com/_next/static/media/imgFallBack.581a9fe3.png'),
        ),
    ]
