# Generated by Django 5.1 on 2024-08-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='media/product/images/'),
        ),
    ]
