# Generated by Django 5.1 on 2024-09-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_projects_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='product/images/'),
        ),
    ]
